dimagi/django-digest

django_digest/models.py, django_digest/utils.py
Gets rid of some deprecation warnings for django 1.7
=> Deprecation

django_digest/backend/storage.py
Reverts dimagi/django-digest#13
Fails HQ tests https://github.com/dimagi/commcare-hq/pull/8163#issuecomment-138351315
cc @czue
=> Revert "Preferred way to atomic transactions"

django_digest/tests.py
=> make tests compatible with django 1.8

django_digest/tests.py
=> add superclass setup()

django_digest/migrations/0001_initial.py, django_digest/models.py
Remove warnings in django 1.9
@sravfeyn @dannyroberts
=> assign on_delete explicitly

django_digest/test/methods/__init__.py
=> replace SortedDict with OrderedDict

django_digest/backend/storage.py
=> stop using value_to_db_datetime

django_digest/utils.py
=> Use better exception format

django_digest/models.py
To be merged with https://github.com/dimagi/commcare-hq/pull/17479
=> include request in call to authenticate

bootstrap.py, django_digest/__init__.py, django_digest/backend/db.py, django_digest/backend/storage.py, django_digest/decorators.py, django_digest/middleware.py, django_digest/migrations/0001_initial.py, django_digest/models.py, django_digest/mysqltestsettings.py, django_digest/south_migrations/0001_initial.py, django_digest/south_migrations/0002_multiple_logins.py, django_digest/south_migrations/0003_require_login_field.py, django_digest/south_migrations/0004_username_length_128.py, django_digest/test/__init__.py, django_digest/test/methods/__init__.py, django_digest/test/methods/basic.py, django_digest/test/methods/detect.py, django_digest/test/methods/digest.py, django_digest/tests.py, django_digest/utils.py, setup.py
=> add 'from __future__ import absolute_import' to all .py files

django_digest/decorators.py
=> python-modernize . -w -f lib2to3.fixes.fix_tuple_params

django_digest/__init__.py
=> python-modernize . -w -f libmodernize.fixes.fix_unicode_type

django_digest/decorators.py
=> replace isCallable with callable

django_digest/tests.py
=> python-modernize . -w -f lib2to3.fixes.fix_ws_comma

django_digest/__init__.py
=> python-modernize . -w -f libmodernize.fixes.fix_xrange_six

django_digest/tests.py
https://trello.com/c/UWGdz9Gl/27-remove-mocker-dependency
confirming that HQ tests still pass: https://github.com/dimagi/commcare-hq/pull/19051
@dimagi/py3
=> replace mocker with mock

bootstrap.py, django_digest/test/methods/digest.py
=> python-modernize . -w -f libmodernize.fixes.fix_urllib_six

bootstrap.py, django_digest/__init__.py, django_digest/backend/db.py, django_digest/backend/storage.py, django_digest/decorators.py, django_digest/middleware.py, django_digest/models.py, django_digest/mysqltestsettings.py, django_digest/test/__init__.py, django_digest/test/methods/__init__.py, django_digest/test/methods/basic.py, django_digest/test/methods/detect.py, django_digest/test/methods/digest.py, django_digest/tests.py, django_digest/testsettings.py, django_digest/utils.py, setup.py
=> python-modernize . -w --future-unicode

django_digest/tests.py
fix tests: https://github.com/dimagi/commcare-hq/pull/19632
@dimagi/py3
=> fix test_authenticate_invalid

django_digest/test/__init__.py
This was the cause of a [very cryptic error](https://travis-ci.org/dimagi/commcare-hq/jobs/347394604)
```
AssertionError: Cannot read more than the available bytes from the HTTP incoming data.
```
@kaapstorm @orangejenny @gbova
=> Reset input for second "request"

django_digest/test/__init__.py
From https://github.com/dimagi/commcare-hq/pull/19633
@kaapstorm
=> Only do the wsgi.input refresh if it's included
